firstNumber = int (input ("please enter your first number"))
secondNumber = int(input ("please enter your second number"))
print (firstNumber+secondNumber)
thirdNumber = int(input ("please enter your first number"))
fourthNumber = int(input("please enter your second number"))
print (thirdNumber-fourthNumber)
fifthNumber = int(input ("please enter your first number"))
sixthNumber = int(input("please enter your second number"))
print (fifthNumber*sixthNumber)
num7 = int(input ("please enter your first number"))
num8 = int(input("please enter your second number"))
print (num7/num8)
num9 = int(input ("please enter your first number"))
num10 = int(input("please enter your second number"))
print (num9//num10)
num11 = int(input ("please enter your first number"))
num12 = int(input("please enter your second number"))
print (num11%num12)
num13 = int(input ("please enter your first number"))
num14 = int(input("please enter your second number"))
num15 = int(input("please enter your third number"))
sum = ((int(num13)+ int(num14)+ int(num15))/ 3)
print (sum)